### ISSUE TITLE
How to create a virtual env. with the repository and installed requirements.

### ISSUE THREAD

**Issue by algebio** [ElementoLab/covid-imc#1]
Hi ElementoLab

Congratulations for your paper, it is a really good job.

I am trying to run your pipeline but I don´t have much experience with Python and I´ll need a bit more help. As recommended, I have tried to create a virtual env. with the repository and installed requirements. For this, I´ve run the first line of your script on my Windows laptop and on a Lynux pc, but I only got error messages, so I must be doing things very wrong.

These are the error messages:

Windows: (running cmd as administrator)
>git clone git@github.com:ElementoLab/covid-imc.git
Cloning into 'covid-imc'...
ssh: connect to host github.com port 22: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Linux:
➤ git clone git@github.com:ElementoLab/covid-imc.git
bash: git: command not found

As I said, I don't have much experience with Python (I feel comfortable with R) and I would appreciate some more instructions on how to start.

Regards
Juan

**Comment by afrendeiro** [comment]
Hi Juan,
Thank you for the kind words.

I don't have experience with Windows, I don't know why cloning the repo isn't working there. You could try cloning using https instead `git clone https://github.com/ElementoLab/covid-imc.git`.
In Linux it seems to me you're missing a `git` installation. If you're using Ubuntu in Windows Subsystem for Linux (WSL) you probably can install git with `sudo apt install git`.

Please note that this repository focuses on data analysis *post*- data processing. If you're interested in processing your data in the same manner have a look at the dedicated pipeline: https://github.com/ElementoLab/imcpipeline which in turn is a variant of https://github.com/BodenmillerGroup/ImcSegmentationPipeline

Let me know how it goes.

**Comment by algebio** [comment]
Hi André
Thank you for your help. 

I'll start with the post - data processing analysis because you made the processed files available and I think it will be easier. I'll install and run imcpipeline after this. (...unless you recommend downloading the raw files and starting from scratch with imcpipeline)

I'm not using WSL on my Windows laptop, I'm using one of our laboratory Linux computers through SSH from my laptop using MobaXterm.

I have spent many of the last hours solving errors related to other processes interfering with the installation but finally I cloned the git (in a folder named Andre), unfortunately I couldn't finish the virtual env. I copied below the last steps just in case you identify the problem: ...maybe a problem with python2 - python3???

Regards
Juan


juan@fms-camb-522224:~/Andre/covid-imc$ sudo apt install virtualenv
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.
juan@fms-camb-522224:~/Andre/covid-imc$ sudo dpkg --configure -a
Setting up libkdf5-2 (2.8.2-2+dfsg-1build1) ...
Setting up sra-toolkit (2.8.2-5+dfsg-1) ...
Setting up med-config (3.0.1ubuntu1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for install-info (6.5.0.dfsg.1-2) ...
Processing triggers for menu (2.1.47ubuntu2.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1.2) ...
juan@fms-camb-522224:~/Andre/covid-imc$ sudo apt install virtualenv
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libblas-dev libjpeg-dev libjpeg-turbo8-dev libjpeg8-dev liblapack-dev liblzma-dev libncurses5-dev libpcre2-16-0 libpcre2-32-0 libpcre2-8-0
  libpcre2-dev libpcre2-posix0 linux-oem-headers-4.15.0-1050 linux-oem-headers-4.15.0-1056 linux-oem-headers-4.15.0-1057 linux-oem-headers-4.15.0-1059
  linux-oem-headers-4.15.0-1064 linux-oem-headers-4.15.0-1065 linux-oem-headers-4.15.0-1066 linux-oem-headers-4.15.0-1067 linux-oem-headers-4.15.0-1069
  linux-oem-headers-4.15.0-1073 linux-oem-headers-4.15.0-1076 linux-oem-headers-4.15.0-1079 linux-oem-headers-4.15.0-1080 linux-oem-headers-4.15.0-1081
  linux-oem-headers-4.15.0-1087 linux-oem-headers-4.15.0-1090 linux-oem-headers-4.15.0-1091 linux-oem-headers-4.15.0-1094
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  python3-virtualenv
The following NEW packages will be installed
  python3-virtualenv virtualenv
0 to upgrade, 2 to newly install, 0 to remove and 179 not to upgrade.
Need to get 47.8 kB of archives.
After this operation, 171 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://gb.archive.ubuntu.com/ubuntu bionic/universe amd64 python3-virtualenv all 15.1.0+ds-1.1 [43.4 kB]
Get:2 http://gb.archive.ubuntu.com/ubuntu bionic/universe amd64 virtualenv all 15.1.0+ds-1.1 [4,476 B]
Fetched 47.8 kB in 0s (322 kB/s)
Selecting previously unselected package python3-virtualenv.
(Reading database ... 593477 files and directories currently installed.)
Preparing to unpack .../python3-virtualenv_15.1.0+ds-1.1_all.deb ...
Unpacking python3-virtualenv (15.1.0+ds-1.1) ...
Selecting previously unselected package virtualenv.
Preparing to unpack .../virtualenv_15.1.0+ds-1.1_all.deb ...
Unpacking virtualenv (15.1.0+ds-1.1) ...
Setting up python3-virtualenv (15.1.0+ds-1.1) ...
Setting up virtualenv (15.1.0+ds-1.1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
juan@fms-camb-522224:~/Andre/covid-imc$ virtualenv .venv
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/juan/Andre/covid-imc/.venv/bin/python2
Also creating executable in /home/juan/Andre/covid-imc/.venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
juan@fms-camb-522224:~/Andre/covid-imc$ source activate .venv/bin/activate
-bash: activate: No such file or directory

**Comment by algebio** [comment]
Sorry. No idea why those lines are crossed 


juan@fms-camb-522224:~/Andre/covid-imc$ sudo apt install virtualenv
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.
juan@fms-camb-522224:~/Andre/covid-imc$ sudo dpkg --configure -a
Setting up libkdf5-2 (2.8.2-2+dfsg-1build1) ...
Setting up sra-toolkit (2.8.2-5+dfsg-1) ...
Setting up med-config (3.0.1ubuntu1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for install-info (6.5.0.dfsg.1-2) ...
Processing triggers for menu (2.1.47ubuntu2.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1.2) ...
juan@fms-camb-522224:~/Andre/covid-imc$ sudo apt install virtualenv
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libblas-dev libjpeg-dev libjpeg-turbo8-dev libjpeg8-dev liblapack-dev liblzma-dev libncurses5-dev libpcre2-16-0 libpcre2-32-0 libpcre2-8-0
  libpcre2-dev libpcre2-posix0 linux-oem-headers-4.15.0-1050 linux-oem-headers-4.15.0-1056 linux-oem-headers-4.15.0-1057 linux-oem-headers-4.15.0-1059
  linux-oem-headers-4.15.0-1064 linux-oem-headers-4.15.0-1065 linux-oem-headers-4.15.0-1066 linux-oem-headers-4.15.0-1067 linux-oem-headers-4.15.0-1069
  linux-oem-headers-4.15.0-1073 linux-oem-headers-4.15.0-1076 linux-oem-headers-4.15.0-1079 linux-oem-headers-4.15.0-1080 linux-oem-headers-4.15.0-1081
  linux-oem-headers-4.15.0-1087 linux-oem-headers-4.15.0-1090 linux-oem-headers-4.15.0-1091 linux-oem-headers-4.15.0-1094
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  python3-virtualenv
The following NEW packages will be installed
  python3-virtualenv virtualenv
0 to upgrade, 2 to newly install, 0 to remove and 179 not to upgrade.
Need to get 47.8 kB of archives.
After this operation, 171 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://gb.archive.ubuntu.com/ubuntu bionic/universe amd64 python3-virtualenv all 15.1.0+ds-1.1 [43.4 kB]
Get:2 http://gb.archive.ubuntu.com/ubuntu bionic/universe amd64 virtualenv all 15.1.0+ds-1.1 [4,476 B]
Fetched 47.8 kB in 0s (322 kB/s)
Selecting previously unselected package python3-virtualenv.
(Reading database ... 593477 files and directories currently installed.)
Preparing to unpack .../python3-virtualenv_15.1.0+ds-1.1_all.deb ...
Unpacking python3-virtualenv (15.1.0+ds-1.1) ...
Selecting previously unselected package virtualenv.
Preparing to unpack .../virtualenv_15.1.0+ds-1.1_all.deb ...
Unpacking virtualenv (15.1.0+ds-1.1) ...
Setting up python3-virtualenv (15.1.0+ds-1.1) ...
Setting up virtualenv (15.1.0+ds-1.1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
juan@fms-camb-522224:~/Andre/covid-imc$ virtualenv .venv
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/juan/Andre/covid-imc/.venv/bin/python2
Also creating executable in /home/juan/Andre/covid-imc/.venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
juan@fms-camb-522224:~/Andre/covid-imc$ source activate .venv/bin/activate
-bash: activate: No such file or directory





juan@fms-camb-522224:~/Andre/covid-imc$ sudo apt install virtualenv
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.
juan@fms-camb-522224:~/Andre/covid-imc$ sudo dpkg --configure -a
Setting up libkdf5-2 (2.8.2-2+dfsg-1build1) ...
Setting up sra-toolkit (2.8.2-5+dfsg-1) ...
Setting up med-config (3.0.1ubuntu1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for install-info (6.5.0.dfsg.1-2) ...
Processing triggers for menu (2.1.47ubuntu2.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1.2) ...
juan@fms-camb-522224:~/Andre/covid-imc$ sudo apt install virtualenv
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libblas-dev libjpeg-dev libjpeg-turbo8-dev libjpeg8-dev liblapack-dev liblzma-dev libncurses5-dev libpcre2-16-0 libpcre2-32-0 libpcre2-8-0
  libpcre2-dev libpcre2-posix0 linux-oem-headers-4.15.0-1050 linux-oem-headers-4.15.0-1056 linux-oem-headers-4.15.0-1057 linux-oem-headers-4.15.0-1059
  linux-oem-headers-4.15.0-1064 linux-oem-headers-4.15.0-1065 linux-oem-headers-4.15.0-1066 linux-oem-headers-4.15.0-1067 linux-oem-headers-4.15.0-1069
  linux-oem-headers-4.15.0-1073 linux-oem-headers-4.15.0-1076 linux-oem-headers-4.15.0-1079 linux-oem-headers-4.15.0-1080 linux-oem-headers-4.15.0-1081
  linux-oem-headers-4.15.0-1087 linux-oem-headers-4.15.0-1090 linux-oem-headers-4.15.0-1091 linux-oem-headers-4.15.0-1094
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  python3-virtualenv
The following NEW packages will be installed
  python3-virtualenv virtualenv
0 to upgrade, 2 to newly install, 0 to remove and 179 not to upgrade.
Need to get 47.8 kB of archives.
After this operation, 171 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://gb.archive.ubuntu.com/ubuntu bionic/universe amd64 python3-virtualenv all 15.1.0+ds-1.1 [43.4 kB]
Get:2 http://gb.archive.ubuntu.com/ubuntu bionic/universe amd64 virtualenv all 15.1.0+ds-1.1 [4,476 B]
Fetched 47.8 kB in 0s (322 kB/s)
Selecting previously unselected package python3-virtualenv.
(Reading database ... 593477 files and directories currently installed.)
Preparing to unpack .../python3-virtualenv_15.1.0+ds-1.1_all.deb ...
Unpacking python3-virtualenv (15.1.0+ds-1.1) ...
Selecting previously unselected package virtualenv.
Preparing to unpack .../virtualenv_15.1.0+ds-1.1_all.deb ...
Unpacking virtualenv (15.1.0+ds-1.1) ...
Setting up python3-virtualenv (15.1.0+ds-1.1) ...
Setting up virtualenv (15.1.0+ds-1.1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
juan@fms-camb-522224:~/Andre/covid-imc$ virtualenv .venv
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/juan/Andre/covid-imc/.venv/bin/python2
Also creating executable in /home/juan/Andre/covid-imc/.venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
juan@fms-camb-522224:~/Andre/covid-imc$ source activate .venv/bin/activate
-bash: activate: No such file or directory

**Comment by algebio** [comment]
Sorry about those crossed lines. Same text here without it.

juan@fms-camb-522224: ~ /Andre/covid-imc$ sudo apt install virtualenv
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.
juan@fms-camb-522224: ~ /Andre/covid-imc$ sudo dpkg --configure -a
Setting up libkdf5-2 (2.8.2-2+dfsg-1build1) ...
Setting up sra-toolkit (2.8.2-5+dfsg-1) ...
Setting up med-config (3.0.1ubuntu1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for install-info (6.5.0.dfsg.1-2) ...
Processing triggers for menu (2.1.47ubuntu2.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1.2) ...
juan@fms-camb-522224: ~ /Andre/covid-imc$ sudo apt install virtualenv
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libblas-dev libjpeg-dev libjpeg-turbo8-dev libjpeg8-dev liblapack-dev liblzma-dev libncurses5-dev libpcre2-16-0 libpcre2-32-0 libpcre2-8-0
  libpcre2-dev libpcre2-posix0 linux-oem-headers-4.15.0-1050 linux-oem-headers-4.15.0-1056 linux-oem-headers-4.15.0-1057 linux-oem-headers-4.15.0-1059
  linux-oem-headers-4.15.0-1064 linux-oem-headers-4.15.0-1065 linux-oem-headers-4.15.0-1066 linux-oem-headers-4.15.0-1067 linux-oem-headers-4.15.0-1069
  linux-oem-headers-4.15.0-1073 linux-oem-headers-4.15.0-1076 linux-oem-headers-4.15.0-1079 linux-oem-headers-4.15.0-1080 linux-oem-headers-4.15.0-1081
  linux-oem-headers-4.15.0-1087 linux-oem-headers-4.15.0-1090 linux-oem-headers-4.15.0-1091 linux-oem-headers-4.15.0-1094
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  python3-virtualenv
The following NEW packages will be installed
  python3-virtualenv virtualenv
0 to upgrade, 2 to newly install, 0 to remove and 179 not to upgrade.
Need to get 47.8 kB of archives.
After this operation, 171 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://gb.archive.ubuntu.com/ubuntu bionic/universe amd64 python3-virtualenv all 15.1.0+ds-1.1 [43.4 kB]
Get:2 http://gb.archive.ubuntu.com/ubuntu bionic/universe amd64 virtualenv all 15.1.0+ds-1.1 [4,476 B]
Fetched 47.8 kB in 0s (322 kB/s)
Selecting previously unselected package python3-virtualenv.
(Reading database ... 593477 files and directories currently installed.)
Preparing to unpack .../python3-virtualenv_15.1.0+ds-1.1_all.deb ...
Unpacking python3-virtualenv (15.1.0+ds-1.1) ...
Selecting previously unselected package virtualenv.
Preparing to unpack .../virtualenv_15.1.0+ds-1.1_all.deb ...
Unpacking virtualenv (15.1.0+ds-1.1) ...
Setting up python3-virtualenv (15.1.0+ds-1.1) ...
Setting up virtualenv (15.1.0+ds-1.1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
juan@fms-camb-522224: ~ /Andre/covid-imc$ virtualenv .venv
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/juan/Andre/covid-imc/.venv/bin/python2
Also creating executable in /home/juan/Andre/covid-imc/.venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
juan@fms-camb-522224: ~ /Andre/covid-imc$ source activate .venv/bin/activate
-bash: activate: No such file or directory

**Comment by afrendeiro** [comment]
Hi Juan,

Sorry you're having so much trouble.
Just to be clear, a virtual environment with `virtualenv` is just one of many options to have a isolated environment. You could also try using conda/miniconda which is a very popular method and has a great support community.

So I had a mistake in my README and the last command should have been just `source .venv/bin/activate` to activate the virtual environment. Here's an introduction to virtualenv which you might find useful: https://realpython.com/python-virtual-environments-a-primer/

So judging from some of the output there, you won't be able to run my code because Python 2 is no longer maintained and I wrote code that is not compatible with Python 2. In fact you'll need at least 3.7.
So you'd need to install a more recent Python version or use a virtual machine with Ubuntu 20.04 for example which only has Python 3 (I think it comes with 3.8.2).


Regardless of the installation issues, I'm not sure what the goal is but the code used in this project builds heavily on my new package [`imc`](https://github.com/ElementoLab/imc) which does the heavy lifting. It's still in development and I intend to publish it too, but it could be interesting if you'd like to try it out, since it comes with both synthetic and small set of real demo data to play with.

**Comment by algebio** [comment]
Hi André

Thank you for the feedback. I have updated to Python 3.7 following this [link](https://askubuntu.com/questions/1173422/how-to-change-virtualenv-interpreter) . I hope I did it right. Then I tried to install the requirements but failed twice (with and without sudo python3)

(env) juan@fms-camb-522224:~/Andre/covid-imc$ pip install -r requirements.txt
Collecting git+ssh://****@github.com/elementolab/imc.git (from -r requirements.txt (line 14))
  Cloning ssh://****@github.com/elementolab/imc.git to /tmp/pip-req-build-_kshhd8p
ERROR: Command errored out with exit status 128: git clone -q 'ssh://****@github.com/elementolab/imc.git' /tmp/pip-req-build-_kshhd8p Check the logs for full command output.


(env) juan@fms-camb-522224:~/Andre/covid-imc$ sudo python3 -m pip install -r requirements.txt
WARNING: The directory '/home/juan/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/juan/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+ssh://git@github.com/elementolab/imc.git (from -r requirements.txt (line 14))
  Cloning ssh://git@github.com/elementolab/imc.git to /tmp/pip-req-build-8a0etlui
  Running command git clone -q ssh://git@github.com/elementolab/imc.git /tmp/pip-req-build-8a0etlui
  git@github.com: Permission denied (publickey).
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
ERROR: Command errored out with exit status 128: git clone -q ssh://git@github.com/elementolab/imc.git /tmp/pip-req-build-8a0etlui Check the logs for full command output.

I tried to check the logs with dmesg but I got an endless list and I got lost there.

**Comment by afrendeiro** [comment]
Hi, sorry for the late reply.
It seems installing the `imc` library failed again because of the usage of the ssh protocol.
You could maybe try `pip install git+https://github.com/ElementoLab/imc.git`.

**Comment by algebio** [comment]
Hi André

I finally finished creating the virtual environment, so we can close this thread. Thank you for all your help, I couldn't have done it without it.

Tomorrow I will try to run the processed files. I understood that this pipeline focuses on data analysis after data processing, so I will download the tiff files from [Zenodo](https://zenodo.org/record/4139443#.X6AdR4j7SMo) and I will run the command process_local. Please correct me if I'm wrong, otherwise you can close the thread. If everything goes well, I'll try with my own data.

I would like to try also imc and imcpipeline but I find them quite challenging for several reasons. I'll try but it will take me time. 

Thanks again for your help.

Regards
Juan

**Comment by BFonseca11** [comment]
Hi Andre,

Great work you have done with the COVID-19 lung tissue samples. I was wondering, do you have the dataset only with the percentage and number of cells for the meta-clusters from the tissue samples for each disease group? Because on your paper, I saw the graphics of the Extended Data 6-7 and I wasn't able to get the precise values. It would be great to have those values. Can you provide them, or explain how to extract this from your dataset?

Thanks in advance,

Regards
Bruna
