### ISSUE TITLE
Unable to run the pipeline

### ISSUE THREAD

**Issue by algebio** [ElementoLab/covid-imc#3]
Hi André 

I´m very sorry to bother you again. I think I haven´t understood well how to run your pipeline. I really need some more basic guidance.  However, I will understand if you´re too busy to create a tutorial for people like me.

I installed the pipeline and I downloaded the tiff files to a newly created folder called "data". Then I run the command "make process_local" but I got this:

juan@fms-camb-522224:~/Andre/covid-imc$ make process_local
for SAMPLE in 20200609_ARDS_1921-01_full_mask.tiff 20200609_ARDS_1921-02_full_mask.tiff 20200609_ARDS_1921-03_full_mask.tiff 20200609_ARDS_1921-04_full_mask.tiff [....the list goes for every tiff...] 20200812_ARDS_SEPSIS_1966-02_full_mask.tiff 20200812_ARDS_SEPSIS_1966-03_full_mask.tiff 20200812_ARDS_SEPSIS_1966-04_full_mask.tiff 20200812_ARDS_SEPSIS_1966-05_full_mask.tiff; do
/bin/sh: 1: Syntax error: end of file unexpected
Makefile:32: recipe for target 'process_local' failed
make: *** [process_local] Error 2
juan@fms-camb-522224:~/Andre/covid-imc$

Sorry again for my lack of expertise and thank you for your patience and help.

Regards
Juan

**Comment by algebio** [comment]
Sorry about that 
juan@fms-camb-522224: ~ /Andre/covid-imc$ make process_local
for SAMPLE in 20200609_ARDS_1921-01_full_mask.tiff 20200609_ARDS_1921-02_full_mask.tiff 20200609_ARDS_1921-03_full_mask.tiff 20200609_ARDS_1921-04_full_mask.tiff 20200609_ARDS_1921-05_full_mask.tiff 20200609_ARDS_1921-06_full_mask.tiff 20200609_ARDS_1921-07_full_mask.tiff 20200609_ARDS_1921-08_full_mask.tiff 20200609_ARDS_1921-09_full_mask.tiff 20200609_ARDS_1921-10_full_mask.tiff .......[the list goes for every tiff].....20200810_ARDS_SEPSIS_19135-07_full_mask.tiff 20200810_ARDS_SEPSIS_19135-08_full_mask.tiff 20200812_ARDS_SEPSIS_1966-01_full_mask.tiff 20200812_ARDS_SEPSIS_1966-02_full_mask.tiff 20200812_ARDS_SEPSIS_1966-03_full_mask.tiff 20200812_ARDS_SEPSIS_1966-04_full_mask.tiff 20200812_ARDS_SEPSIS_1966-05_full_mask.tiff; do
/bin/sh: 1: Syntax error: end of file unexpected
Makefile:32: recipe for target 'process_local' failed
make: *** [process_local] Error 2
juan@fms-camb-522224: ~ /Andre/covid-imc$

**Comment by afrendeiro** [comment]
Hi Juan,
Sorry for the lack of reply, I've been sick in the last week.
Apologies if the instructions haven't been very clear. The processed files available at Zenodo are 2D cell masks. With these one could make pseudocolor images of cells labeled by expression intensity or cluster/metacluster identities for example by using the provided h5ad file (single-cell level data).
Unfortunately due to size restrictions I couldn't upload both the raw data and the image stacks, and therefore I chose the raw unprocessed data. So in order to use pixel-level data one would need to start from the raw data again.

So if you tell me specifically what analysis you're interested in, I may be able to help you start at a given point. Right now I don't have documentation for that but only to start in the beginning. I hope to do a better job at providing documentation for both cases in the final version of the paper and perhaps even provide some interactive visualization to the data, but for now I hope you understand that given the urgency of the project regarding the ongoing pandemic this was not yet possible.

**Comment by algebio** [comment]
Hi André

I hope you feel better now. Scary times to get sick.

Sorry for my delay as well, my week was quite hectic.

Thank you for your clarification. So, I understand that the pipeline failed because the h5ad files were missing. Please close this thread if that was the reason. 

My idea was to try to replicate your figures with the purpose of acquiring experience in doing these analysis. As you saw, I have little experience working with servers and containers, so I get lost at the first error message. I also struggle with the Bodenmiller pipeline, specially to get clear segmentations, so my figures are poor. I need to get to that level ASAP and be able to produce same quality figures. What should I do? What would be your "mentor advice"? 

I understand that this is out of this thread. You can answer directly to my email if you prefer: ecobiologo [at] gmail [dot] com

Regards and thanks
Juan

**Comment by afrendeiro** [comment]
Hi Juan,

Thank you, yes I'm feeling much better now.

Indeed there is considerable technical debt in the field in making analysis of IMC data more accessible to everyone. Unfortunately I don't think my analysis for this particular paper is helping with that either. The Zanotelli/Bodenmiller pipeline is actually probably the friendliest of them out there and is indeed what I used for this project, just packaged differently into https://github.com/ElementoLab/imcpipeline. Still that has the double-edge sword of having the user build their own segmentation model with ilastik: allows customization to the tissue in question, but is less transferable across projects.

I do have plans to make a package enabling that which is currently the `https://github.com/ElementoLab/imc` repository, but it still lacks several features and a lot of documentation.
In any case I still hope to make the code in this repository more documented and easier to run, but I have to focus on some revision work for the time being.

I'll let you know when `imc` package is mature enough - maybe you can help me test/try it out.

Best, Andre

**Comment by algebio** [comment]
Hi André

That´s a great idea. Please let me know when imc is mature enough and I will be very happy to help you test it.

Regards
Juan
