### ISSUE TITLE
Cell location information is missing in the .h5ad file on zenodo

### ISSUE THREAD

**Issue by Mr-Milk** [ElementoLab/covid-imc#7]
Hi, it's so nice that you provide a .h5ad file. However, I found that the cell location information might be missing in the file?

**Comment by afrendeiro** [comment]
Hi,
Thanks for the interest.

The data comes from a technique which does not rely on pre-allocated positions within the image to query marker abundance but measures marker intensity in a scatter grid for a selected region within the tissue - more like conventional imaging with pixels. The position of the cells is then derived by segmenting the acquired image. In that sense the location of the cells isn't a x/y pair coordinate, but a polygon defining the object boundaries, commonly represented as a image mask with instances as different values. That's how I've been using the h5ad file in conjunction with the image masks for spatial analysis.

Of course one can produce XY coordinates for a cell by getting a centroid for example. That may be useful in some applications or too simplistic for others.
Anyway, give me a few days and I'll see if I find some free time to produce centroids for this dataset.

**Comment by Mr-Milk** [comment]
Thanks for the quick response, we also have an IMC machine but there are always some wired glitches so I just wanna get some data to try some analysis. Is the `acquisition_id` in the `obs` field match to the mask image and the `obj_id` match to the cell mask in each image? If that's the case, I could get the location info myself. 

Little suggestion, it may be helpful to other people who want to reuse this dataset if you could explicitly say the meaning of some of these keys.

**Comment by afrendeiro** [comment]
Yes, the `roi` column refers to the specific region of interest within a sample (which has a matching mask) and the `obj_id` the identity of the cell in the mask.

Sorry for the relative lack of documentation. My primary focus was on the research and ensuring reproducibility. Unfortunately re-usability is often hard to get right, and it is a step with little reward in research except in method-driven projects (but definitely deserving a broader discussion than this).
In any case, do you know of a community consensus/best practice on how to annotate the meaning of variables in obs/var (the meta-meta-data I guess)?

I created a file with centroid locations for all cells: https://wcm.box.com/shared/static/ihhs5414d7tgqpsseyy3u7holtpgvng5.gz
At least for now I did not include them in the h5ad as I would have to update the Zenodo deposit, but I might.

For my own future reference:
```python
import pandas as pd
from src.config import prj

locs = prj.quantify_cell_morphology(attributes=["centroid"])
locs = (
    locs.drop("sample", axis=1)
    .rename(columns={"centroid-0": "X", "centroid-1": "Y"})
    .reset_index()[["roi", "obj_id", "X", "Y"]]
)
locs.to_csv("covid-imc.centroids.csv.gz", index=False)
pd.read_csv('https://wcm.box.com/shared/static/ihhs5414d7tgqpsseyy3u7holtpgvng5.gz')
```
```
                              roi  obj_id            X            Y
0              20200728_NL6699-01       6     9.439024   343.780488
1              20200728_NL6699-01       8    13.914530   830.495726
2              20200728_NL6699-01       9    11.911111   331.977778
3              20200728_NL6699-01      10    12.686441   307.610169
4              20200728_NL6699-01      11    17.421053   355.117409
...                           ...     ...          ...          ...
861495  20200701_COVID_11_LATE-11    6648  1491.865672  1344.149254
861496  20200701_COVID_11_LATE-11    6649  1491.568182  1036.227273
861497  20200701_COVID_11_LATE-11    6651  1490.525773    79.783505
861498  20200701_COVID_11_LATE-11    6660  1493.714286  1027.904762
861499  20200701_COVID_11_LATE-11    6669  1493.275862   315.879310

[861500 rows x 4 columns]
```

**Comment by Mr-Milk** [comment]
Well, I believe the best practice would always be to name the variable an intuitive name. But that might be hard sometimes. So, record it in the README file would also be great, since that's the first place people will go if they have some questions with the data. As for the `AnnData` object, the scanpy stores meta information of analysis in the `.uns` field, but I think for most users they won't even look at it.

Thanks a lot for your sharing.
